// Generated by ever-better. This file is yours — edit it.
//
// Every rule below is an ERROR, and every violation that existed when you ran
// `ever-better freeze` is recorded in eslint-suppressions.json. Old code is grandfathered;
// new code is held to the whole standard from the first commit. Do not soften a rule to make
// a red build green — the suppressions file already did that, once, on purpose.
//
// Type assertions are banned outright: `as`, `<T>x`, `!`, `@ts-ignore`, `@ts-nocheck`. Each is a
// claim the compiler could not check and that no reviewer can see. Write a type guard instead —
// `const isThing = (v: unknown): v is Thing => ...` — which is testable, narrows for every
// caller, and fails at the boundary where the data was actually wrong.

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import sonarjs from 'eslint-plugin-sonarjs';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import security from 'eslint-plugin-security';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.vercel/**',
      // Sample scripts shown to users, not library source. They are deliberately terse and
      // some are broken on purpose; holding them to the standard would only teach people to
      // ignore it. Prettier still formats them.
      'examples/**',
      // Test inputs whose exact shape is the thing under test — see .prettierignore.
      'test/fixtures/**',
    ],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },

  js.configs.recommended,
  // Type-aware rules are off: this repo is not TypeScript yet. They are where the real
  // bugs are found, so migrating unlocks the most valuable tier — see `ever-better diagnose`.
  tseslint.configs.recommended,
  sonarjs.configs.recommended,
  security.configs.recommended,
  prettierRecommended,

  { languageOptions: { globals: globals.node } },

  {
    // pm2 ships CommonJS: no "type": "module", and every .js file is loaded by require().
    // Parsing them as ES modules puts them in strict mode, where legacy octal literals are a
    // parse error and the file silently goes unlinted.
    files: ['**/*.js'],
    languageOptions: { sourceType: 'script' },
    rules: {
      // A .js file in a CommonJS package cannot use `import`, so there is nothing a new file
      // could do to satisfy this — it would block every new test and module rather than hold
      // a line. The rule is live for .ts, which is where the migration is heading.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    // Size and complexity guards. These are the ones that turn into refactoring work rather
    // than one-line fixes, which is exactly why they are recorded rather than negotiated.
    rules: {
      'max-lines': ['error', { max: 600, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
      complexity: ['error', 15],
      'max-depth': ['error', 4],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['error', 6],
      'sonarjs/cognitive-complexity': ['error', 15],
    },
  },
  {
    rules: {
      // A loop counter and a discarded binding are not what this is aimed at; a variable called
      // `d` holding a customer record is. `js`, `fs`, `os` are the conventional module aliases,
      // and `io` is the name of the environment variable pm2 reads, not a choice.
      'id-length': [
        'error',
        {
          min: 3,
          exceptions: ['_', 'i', 'j', 'k', 'id', 'ok', 'to', 'up', 'js', 'fs', 'os', 'io'],
        },
      ],
    },
  },
  {
    // UMD wrapper: `define` is guarded by `typeof define === 'function' && define.amd`, so it
    // exists whenever the branch that calls it runs. Recording it would put a false positive
    // at the top of the no-undef backlog.
    files: ['lib/tools/treeify.js'],
    languageOptions: { globals: { define: 'readonly' } },
  },
  {
    // The args-splitting pattern here IS the fix for CVE-2025-5891, and sonarjs reads its five
    // alternatives as backtracking. Measured against pumped input — repeated `a=`, an
    // unterminated quote, repeated `x-` then a quote, repeated `key="` — sixteen times the
    // input costs sixteen times the time, so it is linear and the warning is wrong. Rewriting a
    // security fix to satisfy a false positive is the trade this exception refuses to make.
    // test/programmatic/issue_6075_redos.mocha.js holds the pattern to that behaviour.
    files: ['lib/tools/Config.ts'],
    rules: {
      'sonarjs/super-linear-regex': 'off',
      'sonarjs/regex-complexity': 'off',
    },
  },
  {
    // A spec repeats itself by nature and its length is not a comprehension problem.
    // The mocha globals are declared here rather than recorded as 1165 no-undef violations:
    // an environment the linter was never told about is not a backlog.
    files: ['test/**', 'modules/*/test/**'],
    languageOptions: { globals: globals.mocha },
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'sonarjs/no-duplicate-string': 'off',
      // eslint-plugin-security asks whether untrusted input can reach a dangerous sink. A test
      // builds its own inputs, so the answer is always no — and leaving these on means every
      // test that touches a temp directory or spawns pm2 raises the ceiling, which turns the
      // ratchet into a reason not to write tests.
      'security/detect-non-literal-fs-filename': 'off',
      'security/detect-object-injection': 'off',
      'security/detect-non-literal-require': 'off',
      'security/detect-child-process': 'off',
    },
  },
);
