// Generated by ever-better. This file is yours — edit it.
//
// Every rule below is an ERROR, and every violation that existed when you ran
// `ever-better freeze` is recorded in eslint-suppressions.json. Old code is grandfathered;
// new code is held to the whole standard from the first commit. Do not soften a rule to make
// a red build green — the suppressions file already did that, once, on purpose.
//
// Type assertions are banned outright: `as`, `<T>x`, `!`, `@ts-ignore`, `@ts-nocheck`. Each is a
// claim the compiler could not check and that no reviewer can see. Write a type guard instead —
// `const isThing = (v: unknown): v is Thing => ...` — which is testable, narrows for every
// caller, and fails at the boundary where the data was actually wrong.

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import sonarjs from 'eslint-plugin-sonarjs';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import security from 'eslint-plugin-security';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.vercel/**',
      // Sample scripts shown to users, not library source. They are deliberately terse and
      // some are broken on purpose; holding them to the standard would only teach people to
      // ignore it. Prettier still formats them.
      'examples/**',
      // Test inputs whose exact shape is the thing under test — see .prettierignore.
      'test/fixtures/**',
    ],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },

  js.configs.recommended,
  // Type-aware rules are off: this repo is not TypeScript yet. They are where the real
  // bugs are found, so migrating unlocks the most valuable tier — see `ever-better diagnose`.
  tseslint.configs.recommended,
  sonarjs.configs.recommended,
  security.configs.recommended,
  prettierRecommended,

  { languageOptions: { globals: globals.node } },

  {
    // pm2 ships CommonJS: no "type": "module", and every .js file is loaded by require().
    // Parsing them as ES modules puts them in strict mode, where legacy octal literals are a
    // parse error and the file silently goes unlinted.
    files: ['**/*.js'],
    languageOptions: { sourceType: 'script' },
  },

  {
    // Size and complexity guards. These are the ones that turn into refactoring work rather
    // than one-line fixes, which is exactly why they are recorded rather than negotiated.
    rules: {
      'max-lines': ['error', { max: 600, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
      complexity: ['error', 15],
      'max-depth': ['error', 4],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['error', 6],
      'sonarjs/cognitive-complexity': ['error', 15],
    },
  },
  {
    rules: {
      // A loop counter and a discarded binding are not what this is aimed at; a variable called
      // `d` holding a customer record is. `js`, `fs`, `os` are the conventional module aliases.
      'id-length': [
        'error',
        { min: 3, exceptions: ['_', 'i', 'j', 'k', 'id', 'ok', 'to', 'up', 'js', 'fs', 'os'] },
      ],
    },
  },
  {
    // UMD wrapper: `define` is guarded by `typeof define === 'function' && define.amd`, so it
    // exists whenever the branch that calls it runs. Recording it would put a false positive
    // at the top of the no-undef backlog.
    files: ['lib/tools/treeify.js'],
    languageOptions: { globals: { define: 'readonly' } },
  },
  {
    // A spec repeats itself by nature and its length is not a comprehension problem.
    // The mocha globals are declared here rather than recorded as 1165 no-undef violations:
    // an environment the linter was never told about is not a backlog.
    files: ['test/**', 'modules/*/test/**'],
    languageOptions: { globals: globals.mocha },
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'sonarjs/no-duplicate-string': 'off',
    },
  },
);
